Async hooks
topfreegames/event-context pull request #1
Opened 2019-08-07 17:34 UTC by capella

When one we have an async call the context didn't propagate correctly. To solve this I added the nodejs [async_hooks](https://nodejs.org/api/async_hooks.html#async_hooks_promise_execution_tracking).

2019-08-07 17:40 UTC, capella commented
@cscatolini and @vctandrade, can you both review this PR?
```js
const context = require('tfg-event-context')
const t = require('tfg-event-context-plugin-node')
t.patch()

const ctx = context.createContext('ctx');
ctx.run(async () => {
  console.log(context.getCurrentContext()) // ok
  let p = await Promise.resolve(42)
  console.log(context.getCurrentContext()) // null
})

```
The second context should not be null. This happens because the `revertContext` is called after the async declaration and not after the async function call end.

2019-08-07 18:05 UTC, cscatolini requested changes

2019-08-07 18:05 UTC, cscatolini commented on rollup.config.js
> +// const moduleName = plugin ? `EventContextPlugin${capitalize(plugin)}` : 'EventContext';
remove this line instead of commenting it

2019-08-07 18:05 UTC, cscatolini commented on src/context.js
> +  destroy(asyncId) {}
shouldn't we remove `contextsIds[asyncId]` on destroy?

2019-08-07 18:05 UTC, cscatolini commented on test/promise.js
> +      resetContexts()
aren't you reseting on before() already?

2019-08-07 18:05 UTC, cscatolini commented on test/promise.js
> +        expect(!!getCurrentContext()).to.be.false;
isn't this assert the same as `expect(getCurrentContext()).not.null;`

validating not null is cleaner IMO

2019-08-07 18:05 UTC, cscatolini commented on test/promise.js
> +    it('should then work correctly', done => {
should work correctly with then?

2019-08-07 18:05 UTC, cscatolini commented on test/promise.js
> +    it('should catch work correctly', done => {
should work correctly with catch?

2019-08-07 18:05 UTC, cscatolini commented on test/promise.js
> +        expect(!!getCurrentContext()).to.be.false;
`expect(getCurrentContext()).not.null;`

2019-08-07 18:05 UTC, cscatolini commented on test/promise.js
> +    it('should finally work correctly', done => {
should work correctly with finally?

2019-08-07 18:05 UTC, cscatolini commented on test/promise.js
> +        expect(!!getCurrentContext()).to.be.false;
`expect(getCurrentContext()).not.null;`

2019-08-07 18:05 UTC, cscatolini commented on package.json
> +  "version": "0.5.7",
Let's bump a major version since this is a breaking change.

2019-08-07 19:03 UTC, capella commented on src/context.js
> +  destroy(asyncId) {}
Moved delete `contextsIds[asyncId]` to destroy.

2019-08-07 19:36 UTC, cscatolini reviewed
Please bump a major instead of a minor version. I'd rather wait on Victor's review on this before merging.

2019-08-07 19:36 UTC, cscatolini commented on package.json
> +  "version": "0.6.0",
1.0.0

2019-08-07 20:38 UTC, vctandrade commented
Considering async hooks already work for `setInterval`, `setTimeout`, `setImmediate` and `nextTick`, it would be best if those were not patched twice.

2019-08-07 20:40 UTC, vctandrade commented
Also, since this feature does not work for old NodeJS versions, please specify a strict minimum version on the _package.json_.

2019-08-07 20:44 UTC, vctandrade commented on src/async.js
> +      contextsIds[asyncId] = getCurrentContext()
`getCurrentContext()` could be called only once.

2019-08-07 21:08 UTC, capella commented
I thought about removing `setInterval`, `setTimeout`, `setImmediate` and `nextTick` patches, but the lib needs this  to add the `dispose` functions. In my option, we could remove the `dispose` things and use only the `async_hooks`, what do you think? With this change, we will be unable to stop event listeners created in a context.

2019-08-08 14:26 UTC, capella commented
I added a new commit to remove dispose and I changed a little the logic if contexts.

2019-08-08 16:39 UTC, vctandrade commented
I do not believe removing `dispose` is a problem. It was a secondary feature, which we didn't even use.

2019-08-08 17:01 UTC, vctandrade commented on src/context.js
> +const hook = createHook({
Could you explain why the context logic had to be changed so drastically? I feel like the hooks became harder to understand as its concerns were melded into a once independent context stack implementation.

2019-08-08 17:09 UTC, vctandrade commented on package.json
> +    "node": ">=10.0.0"
Weren't async hooks added on NodeJS v8.1.0?

2019-08-08 18:12 UTC, capella commented on src/context.js
> +const hook = createHook({
The main idea of this change is to not call 'before' and 'after' of async_hook every time. Each async function has `executionAsyncId`, we use this with a map to track the current context. If a new context is context is created we append an element to the array[executionAsyncId], if a new async is create we get the array[triggerAsyncId][-1] and append to array[executionAsyncId]. This may appear harder to understand, but for debugging is much easier, we only need to see the objects of ids and we know all the async calls in a specific moment.

2019-08-08 18:14 UTC, capella commented on package.json
> +    "node": ">=10.0.0"
Yes, the code is compatible with node v8.1.0, but we have a test that uses Promise.finally (only available on node 10).

2019-08-09 02:09 UTC, vctandrade commented on src/context.js
> +const hook = createHook({
Calling `before` and `after` each time does not sound like a problem. After studying the code I do understand what is doing and it does seem correct. However, a straightforward implementation is preferable. Is there a clear benefit in knowing the IDs of all async calls in a specific moment and is this the only way this could be achieved?

2019-08-09 17:38 UTC, capella commented on src/context.js
> +const hook = createHook({
The only benefit is for debugging propose and a don't see any more straightforward way to achieve this. In my opition, the only downside of this implementation is the fact that the logic os, not soo simple to understand in the first moment. However, I think that it is simpler than changing a global variable on all `before` and `after calls.`

2019-08-09 20:17 UTC, vctandrade commented on src/context.js
> +const hook = createHook({
You're still changing a global variable on `init` and `destroy`. It's not that different. But the main point is the separation of concerns. Before, the async hooks module was completely disjoint from the context logic. Now they are intertwined.

Considering the previous implementation, a straightforward way to have all current asyncIDs available for debugging could be just adding/removing them from a set on `init` and `destroy` hooks and having a getter function on the async module.

Regardless, I believe it's just a matter of preference at this point.

2019-08-12 16:14 UTC, cscatolini approved these changes

2019-08-12 16:33 UTC, merged

2020-05-18 17:30 UTC, matheuscscp commented on src/context.js
> +const hook = createHook({
This change is not working correctly in my NodeJS 10.0.0 application =(